{% set name = "SPARC-X" %}
{% set package_name = "sparc" %}
{% set version = "2.0.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://github.com/SPARC-X/{{ package_name }}/archive/refs/tags/v{{ version }}.zip
  sha256: 0190415c9c98dc8026b0a2512baa416163c493a33c8998fe4a4aaf783e02d956

build:
  number: 2

  skip: true  # [not unix]


requirements:
  build:
    - {{ compiler('c') }}
    - make
    - openmpi
    - openblas
    - scalapack
    - fftw * mpi_openmpi_*
  host:
    - openmpi
    - libopenblas
    - scalapack
    - fftw * mpi_openmpi_*
  run:
    - openmpi
    - libopenblas
    - scalapack
    - fftw * mpi_openmpi_*

test:
  source_files:
    - tests/Cu_FCC/standard/*
    - psps/*
  commands:
    - OMPI_MCA_plm_rsh_agent= mpirun -n 1 -wd tests/Cu_FCC/standard/ sparc -name Cu_FCC


about:
  home: https://www.sparc-x.com
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'SPARC: Simulation Package for Ab-initio Real-space Calculations'
  description: |
    SPARC is an open-source software package for the accurate, effcient,
    and scalable solution of the Kohn-Sham density functional theory (DFT) problem
  doc_url: https://github.com/SPARC-X/SPARC/blob/master/doc/Manual.pdf
  dev_url: https://github.com/SPARC-X/SPARC

extra:
  recipe-maintainers:
  - alchem0x2a
